services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - ENABLE_SIGNUP=false
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
    external: true

