#!/bin/sh
# Auto-generated by i3lock_theme_generator.lua
# Generated: 2026-05-12T00:04:37Z
# Themed for i3lock-color (AUR: i3lock-color)
# DO NOT EDIT — regenerate via: require("themes.i3lock_theme_generator").generate()
#
# If fonts don't render, verify the family name matches fontconfig:
#   fc-list | grep -i terminess
#   fc-list | grep -i ubuntusans

i3lock \
  --color=#101112FF \
  --inside-color=#101112E6 \
  --ring-color=#4980ACE6 \
  --insidever-color=#070C11E6 \
  --ringver-color=#91B2CDE6 \
  --insidewrong-color=#91231C40 \
  --ringwrong-color=#91231CE6 \
  --line-uses-ring \
  --separator-color=#2B4C67E6 \
  --verif-color=#D0D8DAFF \
  --wrong-color=#D0D8DAFF \
  --modif-color=#91231CFF \
  --time-color=#D0D8DAFF \
  --date-color=#D0D8DACC \
  --layout-color=#D0D8DACC \
  --keyhl-color=#202324E6 \
  --bshl-color=#91231CE6 \
  --time-font="HeavyData Nerd Font" \
  --time-size=66 \
  --date-font="Terminess Nerd Font" \
  --date-size=21 \
  --verif-font="Terminess Nerd Font" \
  --verif-size=21 \
  --wrong-font="Terminess Nerd Font" \
  --wrong-size=21 \
  --layout-font="Terminess Nerd Font" \
  --layout-size=44 \
  --indicator \
  --radius=190 \
  --ring-width=16 \
  --screen 1 \
  --clock \
  --time-str="%H:%M" \
  --date-str="%A, %Y-%m-%d" \
  --verif-text="Checking..." \
  --wrong-text="Wrong pswd" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys
