[music-arch]
image="quay.io/toolbx/arch-toolbox:latest"
home="/mnt/lucie/distrobox-home/music"
additional_packages="picard pipewire pipewire-pulse pipewire-alsa libpulse git curl fish neovim lua luarocks"
pre_init_hooks="export SHELL=/usr/bin/fish;"
# mnt volumes are already mounted by default
pull=true
replace=false

