# Prune paths - one per line, # for comments
# These directories will be excluded from search
$HOME/Music/DevilplanServerMusic
$HOME/Music/lyghtersMusic
$HOME/Music/UbuntuServerMusicCollections
$HOME/apps
$HOME/go
$HOME/Android
$HOME/.cache
$HOME/.local
$HOME/.wine
$HOME/.steam
$HOME/Code
/mnt/hd1/impulses

