#!/bin/bash

get_theme() {
    # Check which waybar theme is set
    THEMEIS="dark.css"
    SWITCHTO="-dark"
    MODESTR="Dark"
}

update_theme() { 
    THEMEIS="dark.css"
}

update_theme_orig() {
    #set the xfce and GTK theme
    if [[ $VER == "v4" || $VERTO == "v4-" ]]; then
        xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
        gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
    else 
        xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"
        gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"
    fi

    xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
}

get_ver() {
    VER="Luci4"
}

get_ver_orig() {
    VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)
}

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
    VER="Luci4"
}

switch_version() {
    VER="Luci4"
}

switch_version_orig() {
    get_theme
    get_ver
    case $VER in
        v1)
            #we are on v1 so switch to v2
            VERTO="v2-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV2"
        ;;
        
        v2)
            #we are on v2 so switch to v3
            VERTO="v3-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV3"
        ;;

        v3)
            #we are on v3 so switch to v4
            VERTO="v4-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV4"
        ;;

        v4)
            #we are on v4 so switch to v1
            VERTO="v1-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV1"
        ;;
        
    esac
    #set the waybar config
    ln -sf ~/.config/waybar/conf/$VERTO'config.jsonc' ~/.config/waybar/config.jsonc
    #set the waybar theme
    ln -sf ~/.config/waybar/style/$VERTO'style'$SWITCHTO.css ~/.config/waybar/style.css
    #set the wofi theme
    ln -sf ~/.config/wofi/style/$VERTO'style'$SWITCHTO.css ~/.config/wofi/style.css

    #set the background
    if [ -z $SET_BG ]; then
        swww img ~/.config/backgrounds/$VERTO'background'$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
    else
        swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
    fi

    #update the sddm image
    cp -f ~/.config/backgrounds/$VERTO'background'$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

}

switch_keyboard() {
    VER="Luci4"
}

if [[ "$1" == "vswitch" ]]; then
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    restart_waybar
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n'\
'SUPER + C = Start Kitty\n'\
'SUPER + SHIFT + C = Close Window\n'\
'SUPER + ALT + L = Lock Screen\n'\
'SUPER + SHIFT + Q = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + CTL + SPACE = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot\n'\
'SUPER + T = Switch HyprV version\n'\
'ALT + V = Open clipboard manager'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
