#!/bin/bash

get_theme() {
    # Check which waybar theme is set
    THEMEIS="dark.css"
    SWITCHTO="-dark"
    MODESTR="Dark"
}

update_theme() { 
    THEMEIS="dark.css"
}

get_ver() {
    VER="Luci4"
}

restart_waybar() {
    pkill waybar
    waybar & 
}

set_current_background() {
    VER="Luci4"
}

switch_version() {
    VER="Luci4"
}

switch_keyboard() {
    VER="Luci4"
}

if [[ "$1" == "vswitch" ]]; then
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    restart_waybar
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n'\
'SUPER + C = Start Kitty\n'\
'SUPER + SHIFT + C = Close Window\n'\
'SUPER + ALT + L = Lock Screen\n'\
'SUPER + SHIFT + Q = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + CTL + SPACE = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot\n'\
'SUPER + T = Switch HyprV version\n'\
'ALT + V = Open clipboard manager'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
